name: Run Cypress Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Print debug info
        run: |
          echo "Printing directory contents:"
          pwd
          ls -la
          echo "Node version:"
          node -v
          echo "NPM version:"
          npm -v
          echo "Cypress version:"
          npx cypress --version

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headed: false
          record: false
          start: npm start
          wait-on: 'http://localhost:3000' # Adjust if you're running a local app
